#!/usr/bin/env bash

focused_app_data=$(swaymsg -t get_tree | jq ".. | select(.type?) | select(.focused==true) ")
focused_app_id=$( echo "$focused_app_data" | jq ".id" | head -n 1)

#echo $focused_app_data

#echo $focused_app_id
#echo "come testing [$focused_app_id]"

ydotool key ctrl+d

#swaymsg '[class="Chromium-browser" title="Google Meet"]' focus && ydotool key ctrl+d

#swaymsg '[class="Chromium-browser" title="Google Meet"]' focus 2>/var/log/usr/toggle-meet-mute.error 1>/var/log/usr/toggle-meet-mute && ydotool key Ctrl+d 1>/var/log/usr/toggle-meet-mute 2>/var/log/usr/toggle-meet-mute.error && swaymsg "[con_id=$focused_app_id]" focus 2>/var/log/usr/toggle-meet-mute.error
